### ISSUE TITLE
Any plan of npm installation?

### ISSUE THREAD

**Issue by preco21** [LukyVj/Colorify.js#20]
Thank you for creating this amazing library!

I think `npm` will be provided to easy installation for this library.
Is there any plan for supporting `npm`?

**Comment by LukyVj** [comment]
Hi ! Thanks for your support ! :) 

It's already on the pipe :) Keeping you updated !

**Comment by KasperAndersson** [comment]
+1 - any ETA?

**Comment by LukyVj** [comment]
Hey @KasperAndersson ! 
Thanks to @mischah for this! 
You can find it there : https://www.npmjs.com/package/colorify.js

**Comment by mischah** [comment]
:ok_hand:

**Comment by LukyVj** [comment]
Well, wait, it's not done yet 🙄

**Comment by mischah** [comment]
As I said:

> I’m not sure if it would make sense to convert colorify to an UMD module to work as a CommonJS module. Because Colorify.js won’t work in Nodeland and there are comfortable ways to use globals with Browserify.

You now can install and use with browserify with just a little additional effort. 

Sure it might be more comfortable to wrap the existing code with umd boilerplate.

**Comment by preco21** [comment]
Cool! Thanks all!

**Comment by mischah** [comment]
@LukyVj You can close this. Everything works as expected since #28 is merged and `v1.0.3` is published on npm:
![testinstall-colorify mkuehnel localhost -zsh 2016-03-11 22-00-17](https://cloud.githubusercontent.com/assets/441011/13715408/c96db1dc-e7d4-11e5-965b-bbade9e15720.png)

**Comment by LukyVj** [comment]
Yeah thanks @mischah for your active participation
